"""create remaining job portal tables

Revision ID: 0b3c0d074786
Revises: 76756217b865
Create Date: 2026-09-27 15:22:17.238499
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0b3c0d074786"
down_revision: str | None = "76756217b865"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Áp dụng thay đổi schema khi chạy ``alembic upgrade``."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_rate_windows",
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("subject_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "scope IN ('LOGIN', 'REGISTER', 'RESET', 'VERIFY_RESEND')",
            name=op.f("ck_security_rate_windows_valid_scope"),
        ),
        sa.CheckConstraint(
            "request_count >= 0", name=op.f("ck_security_rate_windows_nonnegative_count")
        ),
        sa.PrimaryKeyConstraint(
            "scope", "subject_hash", "window_start", name=op.f("pk_security_rate_windows")
        ),
    )
    op.create_table(
        "ai_rate_windows",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("feature", sa.String(length=24), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "feature IN ('MATCH_EXPLANATION', 'JD_DRAFT')",
            name=op.f("ck_ai_rate_windows_valid_feature"),
        ),
        sa.CheckConstraint("request_count >= 0", name=op.f("ck_ai_rate_windows_nonnegative_count")),
        sa.CheckConstraint(
            "reserved_tokens >= 0", name=op.f("ck_ai_rate_windows_nonnegative_reserved_tokens")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_rate_windows_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "feature", "window_start", name=op.f("pk_ai_rate_windows")
        ),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS', 'DENIED', 'FAILURE')", name=op.f("ck_audit_logs_valid_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_created",
        "audit_logs",
        [sa.literal_column("created_at DESC"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_entity_created",
        "audit_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resource_type IS NULL OR resource_type IN ('JOB', 'APPLICATION', 'INTERVIEW', 'OFFER', 'COMPANY')",
            name=op.f("ck_notifications_valid_resource_type"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("user_id", "event_key", name="uq_notifications_user_event"),
    )
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC"), "id"],
        unique=False,
    )
    op.create_table(
        "cv_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("template_code", sa.String(length=32), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "template_code = 'BASIC_V1'", name=op.f("ck_cv_documents_valid_template")
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_cv_documents_positive_revision")),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_cv_documents_applicant_id_applicants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cv_documents")),
    )
    op.create_table(
        "email_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("notification_id", sa.Uuid(), nullable=True),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("template_code", sa.String(length=64), nullable=False),
        sa.Column("payload_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED')",
            name=op.f("ck_email_deliveries_valid_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_email_deliveries_nonnegative_attempts")),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_email_deliveries_notification_id_notifications"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_email_deliveries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_deliveries")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_email_deliveries_dedup_key")),
    )
    op.create_index(
        "ix_email_deliveries_due", "email_deliveries", ["status", "next_attempt_at"], unique=False
    )
    op.create_index(
        "ix_email_deliveries_processing_lease",
        "email_deliveries",
        ["locked_until"],
        unique=False,
        postgresql_where=sa.text("status = 'PROCESSING'"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("benefits", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("employment_type", sa.String(length=16), nullable=True),
        sa.Column("work_mode", sa.String(length=8), nullable=True),
        sa.Column("seniority", sa.String(length=16), nullable=True),
        sa.Column("experience_min_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("vacancy_count", sa.Integer(), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("is_negotiable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="VND", nullable=False),
        sa.Column("salary_period", sa.String(length=8), server_default="MONTH", nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="DRAFT", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closure_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'VND'", name=op.f("ck_jobs_vnd_only")),
        sa.CheckConstraint(
            "employment_type IS NULL OR employment_type IN ('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT')",
            name=op.f("ck_jobs_valid_employment_type"),
        ),
        sa.CheckConstraint("salary_period = 'MONTH'", name=op.f("ck_jobs_monthly_salary_only")),
        sa.CheckConstraint(
            "seniority IS NULL OR seniority IN ('INTERN', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', 'MANAGER')",
            name=op.f("ck_jobs_valid_seniority"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_APPROVAL', 'REJECTED', 'PUBLISHED', 'CLOSED')",
            name=op.f("ck_jobs_valid_status"),
        ),
        sa.CheckConstraint(
            "work_mode IS NULL OR work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')",
            name=op.f("ck_jobs_valid_work_mode"),
        ),
        sa.CheckConstraint(
            "(is_negotiable AND salary_min IS NULL AND salary_max IS NULL) OR (NOT is_negotiable AND salary_min IS NOT NULL AND salary_max IS NOT NULL)",
            name=op.f("ck_jobs_salary_negotiability_consistency"),
        ),
        sa.CheckConstraint(
            "experience_min_years IS NULL OR experience_min_years >= 0",
            name=op.f("ck_jobs_nonnegative_experience"),
        ),
        sa.CheckConstraint(
            "salary_max IS NULL OR salary_max >= 0", name=op.f("ck_jobs_nonnegative_salary_max")
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_max >= salary_min",
            name=op.f("ck_jobs_valid_salary_range"),
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_min >= 0", name=op.f("ck_jobs_nonnegative_salary_min")
        ),
        sa.CheckConstraint(
            "vacancy_count IS NULL OR vacancy_count > 0", name=op.f("ck_jobs_positive_vacancy")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_jobs_positive_version")),
        sa.ForeignKeyConstraint(
            ["category_id"], ["job_categories.id"], name=op.f("fk_jobs_category_id_job_categories")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_jobs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_jobs_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_jobs_location_id_locations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_category_location", "jobs", ["category_id", "location_id"], unique=False
    )
    op.create_index("ix_jobs_company_status", "jobs", ["company_id", "status"], unique=False)
    op.create_index(
        "ix_jobs_full_text",
        "jobs",
        [
            sa.literal_column(
                "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(requirements, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_jobs_public_search",
        "jobs",
        ["status", "deadline", sa.literal_column("created_at DESC"), "id"],
        unique=False,
    )
    op.create_table(
        "ai_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("feature", sa.String(length=24), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("input_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "feature <> 'MATCH_EXPLANATION' OR (applicant_id IS NOT NULL AND job_id IS NOT NULL)",
            name=op.f("ck_ai_operations_match_has_applicant_and_job"),
        ),
        sa.CheckConstraint(
            "feature IN ('MATCH_EXPLANATION', 'JD_DRAFT')",
            name=op.f("ck_ai_operations_valid_feature"),
        ),
        sa.CheckConstraint(
            "status IN ('SUCCEEDED', 'FAILED')", name=op.f("ck_ai_operations_valid_status")
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_ai_operations_nonnegative_input_tokens"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_ai_operations_nonnegative_output_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_ai_operations_applicant_id_applicants"),
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_ai_operations_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_ai_operations_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_operations")),
    )
    op.create_index(
        "ix_ai_operations_cache",
        "ai_operations",
        ["requested_by", "feature", "input_hash", "expires_at"],
        unique=False,
    )
    op.create_table(
        "job_skills",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_job_skills_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name=op.f("fk_job_skills_skill_id_skills")
        ),
        sa.PrimaryKeyConstraint("job_id", "skill_id", name=op.f("pk_job_skills")),
    )
    op.create_index("ix_job_skills_skill_job", "job_skills", ["skill_id", "job_id"], unique=False)
    op.create_table(
        "job_status_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor_type", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('USER', 'SYSTEM')", name=op.f("ck_job_status_history_valid_actor_type")
        ),
        sa.CheckConstraint(
            "to_status IN ('DRAFT', 'PENDING_APPROVAL', 'REJECTED', 'PUBLISHED', 'CLOSED')",
            name=op.f("ck_job_status_history_valid_to_status"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"], ["users.id"], name=op.f("fk_job_status_history_changed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_status_history_job_id_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_status_history")),
    )
    op.create_index(
        "ix_job_status_history_job_created",
        "job_status_history",
        ["job_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("cv_document_id", sa.Uuid(), nullable=True),
        sa.Column("document_revision", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'GENERATED' AND cv_document_id IS NOT NULL AND document_revision IS NOT NULL) OR (source = 'UPLOAD' AND cv_document_id IS NULL AND document_revision IS NULL)",
            name=op.f("ck_resumes_source_document_consistency"),
        ),
        sa.CheckConstraint(
            "source IN ('UPLOAD', 'GENERATED')", name=op.f("ck_resumes_valid_source")
        ),
        sa.CheckConstraint(
            "deleted_at IS NULL OR NOT is_default", name=op.f("ck_resumes_deleted_not_default")
        ),
        sa.CheckConstraint(
            "document_revision IS NULL OR document_revision >= 1",
            name=op.f("ck_resumes_positive_revision"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 5242880", name=op.f("ck_resumes_valid_size")
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"], ["applicants.id"], name=op.f("fk_resumes_applicant_id_applicants")
        ),
        sa.ForeignKeyConstraint(
            ["cv_document_id"],
            ["cv_documents.id"],
            name=op.f("fk_resumes_cv_document_id_cv_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
        sa.UniqueConstraint("id", "applicant_id", name="uq_resumes_id_applicant_id"),
        sa.UniqueConstraint("storage_key", name=op.f("uq_resumes_storage_key")),
    )
    op.create_index(
        "uq_resumes_active_default",
        "resumes",
        ["applicant_id"],
        unique=True,
        postgresql_where=sa.text("is_default AND deleted_at IS NULL"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column("contact_name", sa.String(length=150), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="APPLIED", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('HIRED', 'REJECTED', 'WITHDRAWN')) = (ended_at IS NOT NULL)",
            name=op.f("ck_applications_terminal_has_end_time"),
        ),
        sa.CheckConstraint(
            "status IN ('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN')",
            name=op.f("ck_applications_valid_status"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_applications_positive_version")),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_applications_applicant_id_applicants"),
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_applications_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["resume_id", "applicant_id"],
            ["resumes.id", "resumes.applicant_id"],
            name="fk_applications_resume_applicant_resumes",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("applicant_id", "job_id", name="uq_applications_applicant_job"),
    )
    op.create_index(
        "ix_applications_applicant_created",
        "applications",
        ["applicant_id", sa.literal_column("created_at DESC"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_applications_job_status_created",
        "applications",
        ["job_id", "status", sa.literal_column("created_at DESC"), "id"],
        unique=False,
    )
    op.create_table(
        "application_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_notes_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_application_notes_author_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_notes")),
    )
    op.create_table(
        "application_status_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('USER', 'SYSTEM')",
            name=op.f("ck_application_status_history_valid_actor_type"),
        ),
        sa.CheckConstraint(
            "to_status IN ('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN')",
            name=op.f("ck_application_status_history_valid_to_status"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_status_history_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_application_status_history_changed_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_status_history")),
    )
    op.create_index(
        "ix_application_status_history_application_created",
        "application_status_history",
        ["application_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "interviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("meeting_url", sa.String(length=2048), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("interviewer_name", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="SCHEDULED", nullable=False),
        sa.Column("result", sa.String(length=16), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(mode = 'ONLINE' AND meeting_url IS NOT NULL) OR (mode = 'OFFLINE' AND address IS NOT NULL)",
            name=op.f("ck_interviews_mode_location_required"),
        ),
        sa.CheckConstraint(
            "(status = 'COMPLETED' AND result IN ('PASS', 'FAIL', 'UNDECIDED')) OR (status <> 'COMPLETED' AND result IS NULL)",
            name=op.f("ck_interviews_result_only_when_completed"),
        ),
        sa.CheckConstraint("mode IN ('ONLINE', 'OFFLINE')", name=op.f("ck_interviews_valid_mode")),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR cancellation_reason IS NOT NULL",
            name=op.f("ck_interviews_cancelled_has_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')",
            name=op.f("ck_interviews_valid_status"),
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_interviews_valid_time_range")),
        sa.CheckConstraint("round_number > 0", name=op.f("ck_interviews_positive_round")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_interviews_positive_version")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_interviews_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_interviews_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interviews")),
        sa.UniqueConstraint(
            "application_id", "round_number", name="uq_interviews_application_round"
        ),
    )
    op.create_index(
        "ix_interviews_application_status_starts",
        "interviews",
        ["application_id", "status", "starts_at"],
        unique=False,
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("salary", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="VND", nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("response_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="DRAFT", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_note", sa.Text(), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawal_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'VND'", name=op.f("ck_offers_vnd_only")),
        sa.CheckConstraint(
            "status <> 'WITHDRAWN' OR (withdrawn_at IS NOT NULL AND withdrawal_reason IS NOT NULL)",
            name=op.f("ck_offers_withdrawal_details_required"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED')",
            name=op.f("ck_offers_valid_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('ACCEPTED', 'REJECTED') OR responded_at IS NOT NULL",
            name=op.f("ck_offers_response_time_required"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED') OR sent_at IS NOT NULL",
            name=op.f("ck_offers_sent_time_required"),
        ),
        sa.CheckConstraint("salary > 0", name=op.f("ck_offers_positive_salary")),
        sa.CheckConstraint("sequence_number > 0", name=op.f("ck_offers_positive_sequence")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_offers_positive_version")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_offers_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_offers_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
        sa.UniqueConstraint(
            "application_id", "sequence_number", name="uq_offers_application_sequence"
        ),
    )
    op.create_index(
        "ix_offers_application_status", "offers", ["application_id", "status"], unique=False
    )
    op.create_index(
        "ix_offers_status_deadline", "offers", ["status", "response_deadline"], unique=False
    )
    op.create_index(
        "uq_offers_accepted_application",
        "offers",
        ["application_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACCEPTED'"),
    )
    op.create_index(
        "uq_offers_active_application",
        "offers",
        ["application_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('DRAFT', 'SENT')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Hoàn tác thay đổi schema khi chạy ``alembic downgrade``."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_offers_active_application",
        table_name="offers",
        postgresql_where=sa.text("status IN ('DRAFT', 'SENT')"),
    )
    op.drop_index(
        "uq_offers_accepted_application",
        table_name="offers",
        postgresql_where=sa.text("status = 'ACCEPTED'"),
    )
    op.drop_index("ix_offers_status_deadline", table_name="offers")
    op.drop_index("ix_offers_application_status", table_name="offers")
    op.drop_table("offers")
    op.drop_index("ix_interviews_application_status_starts", table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(
        "ix_application_status_history_application_created", table_name="application_status_history"
    )
    op.drop_table("application_status_history")
    op.drop_table("application_notes")
    op.drop_index("ix_applications_job_status_created", table_name="applications")
    op.drop_index("ix_applications_applicant_created", table_name="applications")
    op.drop_table("applications")
    op.drop_index(
        "uq_resumes_active_default",
        table_name="resumes",
        postgresql_where=sa.text("is_default AND deleted_at IS NULL"),
    )
    op.drop_table("resumes")
    op.drop_index("ix_job_status_history_job_created", table_name="job_status_history")
    op.drop_table("job_status_history")
    op.drop_index("ix_job_skills_skill_job", table_name="job_skills")
    op.drop_table("job_skills")
    op.drop_index("ix_ai_operations_cache", table_name="ai_operations")
    op.drop_table("ai_operations")
    op.drop_index("ix_jobs_public_search", table_name="jobs")
    op.drop_index("ix_jobs_full_text", table_name="jobs", postgresql_using="gin")
    op.drop_index("ix_jobs_company_status", table_name="jobs")
    op.drop_index("ix_jobs_category_location", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        "ix_email_deliveries_processing_lease",
        table_name="email_deliveries",
        postgresql_where=sa.text("status = 'PROCESSING'"),
    )
    op.drop_index("ix_email_deliveries_due", table_name="email_deliveries")
    op.drop_table("email_deliveries")
    op.drop_table("cv_documents")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(
        "ix_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_table("notifications")
    op.drop_index("ix_audit_logs_entity_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("ai_rate_windows")
    op.drop_table("security_rate_windows")
    # ### end Alembic commands ###
