"""create company tables

Revision ID: 4848cf5312ab
Revises: 27e3d49f49a5
Create Date: 2026-09-21 14:53:27.398731
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4848cf5312ab"
down_revision: str | None = "27e3d49f49a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Áp dụng thay đổi schema khi chạy ``alembic upgrade``."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("registration_number", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("size_band", sa.String(length=16), nullable=False),
        sa.Column("website_url", sa.String(length=2048), nullable=True),
        sa.Column("logo_key", sa.Text(), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verification_status", sa.String(length=16), server_default="PENDING", nullable=False
        ),
        sa.Column("verification_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "size_band IN ('1_10', '11_50', '51_200', '201_500', '501_1000', 'ABOVE_1000')",
            name=op.f("ck_companies_valid_size_band"),
        ),
        sa.CheckConstraint(
            "status <> 'SUSPENDED' OR suspension_reason IS NOT NULL",
            name=op.f("ck_companies_suspended_has_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED')", name=op.f("ck_companies_valid_status")
        ),
        sa.CheckConstraint(
            "verification_status <> 'REJECTED' OR verification_note IS NOT NULL",
            name=op.f("ck_companies_rejected_has_note"),
        ),
        sa.CheckConstraint(
            "verification_status IN ('PENDING', 'VERIFIED', 'REJECTED')",
            name=op.f("ck_companies_valid_verification_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_companies_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_companies_location_id_locations")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_companies_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("registration_number", name=op.f("uq_companies_registration_number")),
    )
    op.create_table(
        "company_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED')",
            name=op.f("ck_company_invitations_valid_status"),
        ),
        sa.CheckConstraint(
            "(accepted_by IS NULL) = (accepted_at IS NULL)",
            name=op.f("ck_company_invitations_acceptance_fields_together"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by"], ["users.id"], name=op.f("fk_company_invitations_accepted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_invitations_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.id"], name=op.f("fk_company_invitations_invited_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_company_invitations_token_hash")),
    )
    op.create_index(
        "uq_company_invitations_pending_email",
        "company_invitations",
        ["company_id", "email"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "company_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("membership_role", sa.String(length=8), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "membership_role IN ('OWNER', 'MEMBER')",
            name=op.f("ck_company_memberships_valid_membership_role"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_memberships_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_company_memberships_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_memberships")),
    )
    op.create_index(
        "uq_company_memberships_active_owner",
        "company_memberships",
        ["company_id"],
        unique=True,
        postgresql_where=sa.text("membership_role = 'OWNER' AND left_at IS NULL"),
    )
    op.create_index(
        "uq_company_memberships_active_user",
        "company_memberships",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("left_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Hoàn tác thay đổi schema khi chạy ``alembic downgrade``."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_company_memberships_active_user",
        table_name="company_memberships",
        postgresql_where=sa.text("left_at IS NULL"),
    )
    op.drop_index(
        "uq_company_memberships_active_owner",
        table_name="company_memberships",
        postgresql_where=sa.text("membership_role = 'OWNER' AND left_at IS NULL"),
    )
    op.drop_table("company_memberships")
    op.drop_index(
        "uq_company_invitations_pending_email",
        table_name="company_invitations",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("company_invitations")
    op.drop_table("companies")
    # ### end Alembic commands ###
