"""create applicant profile tables

Revision ID: 76756217b865
Revises: 4848cf5312ab
Create Date: 2026-09-21 15:18:20.201871
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "76756217b865"
down_revision: str | None = "4848cf5312ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Áp dụng thay đổi schema khi chạy ``alembic upgrade``."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applicants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("headline", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("preferred_location_id", sa.Uuid(), nullable=True),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("desired_salary_min", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("desired_salary_max", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("preferred_work_mode", sa.String(length=8), nullable=True),
        sa.Column("preferred_employment_type", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "preferred_employment_type IS NULL OR preferred_employment_type IN ('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT')",
            name=op.f("ck_applicants_valid_employment_type"),
        ),
        sa.CheckConstraint(
            "preferred_work_mode IS NULL OR preferred_work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')",
            name=op.f("ck_applicants_valid_work_mode"),
        ),
        sa.CheckConstraint(
            "desired_salary_max IS NULL OR desired_salary_max >= 0",
            name=op.f("ck_applicants_nonnegative_salary_max"),
        ),
        sa.CheckConstraint(
            "desired_salary_min IS NULL OR desired_salary_max IS NULL OR desired_salary_max >= desired_salary_min",
            name=op.f("ck_applicants_valid_salary_range"),
        ),
        sa.CheckConstraint(
            "desired_salary_min IS NULL OR desired_salary_min >= 0",
            name=op.f("ck_applicants_nonnegative_salary_min"),
        ),
        sa.CheckConstraint(
            "years_experience IS NULL OR years_experience >= 0",
            name=op.f("ck_applicants_nonnegative_years_experience"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_applicants_location_id_locations")
        ),
        sa.ForeignKeyConstraint(
            ["preferred_location_id"],
            ["locations.id"],
            name=op.f("fk_applicants_preferred_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_applicants_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applicants")),
        sa.UniqueConstraint("user_id", name=op.f("uq_applicants_user_id")),
    )
    op.create_table(
        "applicant_educations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("degree", sa.String(length=100), nullable=True),
        sa.Column("field_of_study", sa.String(length=150), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_applicant_educations_valid_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_applicant_educations_applicant_id_applicants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applicant_educations")),
    )
    op.create_table(
        "applicant_experiences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("job_title", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_applicant_experiences_valid_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_applicant_experiences_applicant_id_applicants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applicant_experiences")),
    )
    op.create_table(
        "applicant_skills",
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_applicant_skills_applicant_id_applicants"),
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name=op.f("fk_applicant_skills_skill_id_skills")
        ),
        sa.PrimaryKeyConstraint("applicant_id", "skill_id", name=op.f("pk_applicant_skills")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Hoàn tác thay đổi schema khi chạy ``alembic downgrade``."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("applicant_skills")
    op.drop_table("applicant_experiences")
    op.drop_table("applicant_educations")
    op.drop_table("applicants")
    # ### end Alembic commands ###
